### ISSUE TITLE
Error when running saxi --firmware-version command

### ISSUE THREAD

**Issue by lukehaas** [nornagon/saxi#124]
I'm seeing the following error when running the `saxi --firmware-version` command:

```
/home/luke/.config/nvm/versions/node/v16.18.0/lib/node_modules/saxi/dist/server/ebb.js:28
        this.writer = this.port.writable.getWriter();
                                         ^

TypeError: Cannot read properties of undefined (reading 'getWriter')
    at new EBB (/home/luke/.config/nvm/versions/node/v16.18.0/lib/node_modules/saxi/dist/server/ebb.js:28:42)
    at Object.<anonymous> (/home/luke/.config/nvm/versions/node/v16.18.0/lib/node_modules/saxi/dist/server/server.js:345:24)
    at Generator.next (<anonymous>)
    at fulfilled (/home/luke/.config/nvm/versions/node/v16.18.0/lib/node_modules/saxi/dist/server/server.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Saxi version: 0.15.0
Node version: 16.18.0
OS: Raspbian Linux

**Comment by alexrudd2** [comment]
Confirmed.  This was broken by the WebSerial rewrite, and works in `0.14.0`.

```
❯ saxi --version
0.15.0
❯ saxi --firmware-version
/opt/homebrew/lib/node_modules/saxi/dist/server/ebb.js:28
        this.writer = this.port.writable.getWriter();
                                         ^

TypeError: Cannot read properties of undefined (reading 'getWriter')
    at new EBB (/opt/homebrew/lib/node_modules/saxi/dist/server/ebb.js:28:42)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/saxi/dist/server/server.js:345:24)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/homebrew/lib/node_modules/saxi/dist/server/server.js:5:58)

Node.js v20.3.0
```
```
❯ saxi --version
0.14.0
❯ saxi --firmware-version
EBBv13_and_above EB Firmware Version 2.7.0
```
