### ISSUE TITLE
Getting firmware version doesn't work in 0.15.0

### ISSUE THREAD

**Issue by alexrudd2** [nornagon/saxi#157]
```
❯ saxi --version
0.15.0
❯ saxi --firmware-version
/opt/homebrew/lib/node_modules/saxi/dist/server/ebb.js:28
        this.writer = this.port.writable.getWriter();
                                         ^

TypeError: Cannot read properties of undefined (reading 'getWriter')
    at new EBB (/opt/homebrew/lib/node_modules/saxi/dist/server/ebb.js:28:42)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/saxi/dist/server/server.js:345:24)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/homebrew/lib/node_modules/saxi/dist/server/server.js:5:58)

Node.js v20.3.0
```
```
❯ saxi --version
0.14.0
❯ saxi --firmware-version
EBBv13_and_above EB Firmware Version 2.7.0
```

**Comment by alexrudd2** [comment]
Dupe of https://github.com/nornagon/saxi/issues/124
