### ISSUE TITLE
Raspberry Pi install failing

### ISSUE THREAD

**Issue by jimmykl** [nornagon/saxi#75]
I'm having some trouble installing on a Raspberry Pi

Following the instructions I can't run the `saxi` command after it finishes installing, it works called from the `~/.npm_global/bin` directory but I get this error:

```
/home/pi/.npm_global/lib/node_modules/saxi/dist/server/cli.js:37
    yargs_1.default.strict()
                    ^

TypeError: yargs_1.default.strict is not a function
    at Object.cli (/home/pi/.npm_global/lib/node_modules/saxi/dist/server/cli.js:37:21)
    at Object.<anonymous> (/home/pi/.npm_global/lib/node_modules/saxi/cli.js:2:30)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by jimmykl** [comment]
Sorry fixed this with a fresh start and following the instructions more closely – please delete!
